server:
  port: 8083

spring:
  application:
    name: API-GATEWAY
    
  cloud:
    gateway:
      routes:
      - id: MOTOR-SERVICE
        uri: lb://MOTOR-SERVICE
        predicates:
        - Path=/motor/**
          
      - id: CUSTOMER-SERVICE
        uri: lb://CUSTOMER-SERVICE
        predicates:
        - Path=/customer/**